// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SibemWebApi.Data;

#nullable disable

namespace SibemWebApi.Migrations
{
    [DbContext(typeof(SibemDbContext))]
    partial class SibemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SibemWebApi.Models.BemModel", b =>
                {
                    b.Property<string>("dependencia")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("id_bem")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("id_igreja")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.ToTable("bens");
                });

            modelBuilder.Entity("SibemWebApi.Models.IgrejaModel", b =>
                {
                    b.Property<string>("endereco")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("foto")
                        .HasColumnType("longtext");

                    b.Property<string>("id_igreja")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("id_setor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("igreja")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("lastInventario")
                        .HasColumnType("longtext");

                    b.Property<int>("situacao")
                        .HasColumnType("int");

                    b.ToTable("igrejas");
                });

            modelBuilder.Entity("SibemWebApi.Models.InventarioModel", b =>
                {
                    b.Property<int>("bens")
                        .HasColumnType("int");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("id_igreja")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("id_inventario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("inicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("inventariantes")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("responsaveis")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("tempo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("termino")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("pdf")
                        .HasColumnType("longtext");

                    b.ToTable("inventario");
                });
#pragma warning restore 612, 618
        }
    }
}
